#ifndef GLOBALS_H
#define GLOBALS_H

#include <stdbool.h>

#define RENDER_SCALE 1

#define RENDER_WIDTH 240 * RENDER_SCALE
#define RENDER_HEIGHT 160 * RENDER_SCALE

#define WINDOW_SCALE 3
#define WINDOW_WIDTH 400 * WINDOW_SCALE
#define WINDOW_HEIGHT 240 * WINDOW_SCALE

#define FRAME_LIMITING true
#define TARGET_FPS 60
#define TARGET_FRAME_TIME (1000 / TARGET_FPS)

#define GBA_WINDOW_START_X 80 * WINDOW_SCALE
#define GBA_WINDOW_START_Y 40 * WINDOW_SCALE
#define GBA_WINDOW_END_X 320 * WINDOW_SCALE
#define GBA_WINDOW_END_Y 200 * WINDOW_SCALE
#define GBA_WINDOW_WIDTH (GBA_WINDOW_END_X - GBA_WINDOW_START_X)
#define GBA_WINDOW_HEIGHT (GBA_WINDOW_END_Y - GBA_WINDOW_START_Y)
#define GBA_LIGHT_X 369 * WINDOW_SCALE
#define GBA_LIGHT_Y 24 * WINDOW_SCALE

#define USE_GBA_BORDER true
#define SHOW_FPS true

extern int WIDTH;
extern int HEIGHT;

#endif // GLOBALS_H
